language: node_js
sudo: false
node_js:
  - node
script:
  - if [[ "${TRAVIS_BRANCH}" = "UPGRADE" ]]; then; git checkout master && yarn upgrade:local && yarn deploy:patch; fi
  - yarn test:cov
deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true