language: node_js
sudo: false
node_js:
  - node
script:
  - if [[ "${TRAVIS_EVENT_TYPE}" = "cron" ]]; git checkout master && then yarn upgrade:local && yarn deploy:patch ; fi
  - yarn test:cov
deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true